int add(int a, int b);
void times_table(void);
void jack_bauer(void);
int print_last_digit(long);
int _abs(int);
int _putchar(char c);
void print_alphabet();
void print_alphabet_x10();
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
